ログイン機能追加
tomoya0220-gz/datyorogu pull request #6
Opened 2024-01-21 05:01 UTC by tomoya0220-gz

# WHAT
- Deviseを使わずにログイン機能の実装しました。以下のURLサイトを参考に進めました。
　(https://autovice.jp/articles/168)

2024-01-22 01:06 UTC, tatsuro1997 reviewed
- PRにIssueを紐付ける
- 画面の変更がある場合はPRメッセージにスクショを貼っていただくとわかりやすくて良いです。

2024-01-22 01:06 UTC, tatsuro1997 commented on config/routes.rb
> +  get 'users/show/:id', to:'users#show', as:'show_user'
これだとRESTAPIになっていないのでこのようにするか、
```suggestion
  get 'users/:id', to:'users#show'
```
以下のようにするのがよいです。（onlyは必要によって変えてください）
```rb
resources :users, only: %i(show update)
```

2024-01-23 01:29 UTC, tatsuro1997 commented
今の段階でRubocopを入れて、コードをきれいにするようにしておいた方が良いです

2024-01-29 01:29 UTC, tatsuro1997 requested changes

2024-01-29 01:29 UTC, tatsuro1997 commented on config/routes.rb
> +<<<<<<< HEAD
コンフリクト直っていないですが大丈夫ですかね

2024-01-29 01:29 UTC, tatsuro1997 commented on config/routes.rb
> +<<<<<<< HEAD
[こちら](https://github.com/tomoya0220-gz/datyorogu/pull/21#discussion_r1468986330)と同様です

2024-01-29 13:11 UTC, tomoya0220-gz commented
指摘を受けたコンフリクトの対応とログインが正常にできることを確認しましたので、レビューをよろしくお願いします！

2024-01-30 01:02 UTC, tatsuro1997 approved these changes

2024-01-30 03:49 UTC, merged